/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projek_rizki_nugraha;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Refqi
 */
public class regis extends javax.swing.JFrame {
    
    Statement st;
    ResultSet rs;
    koneksi koneksi;
    /**
     * Creates new form regis
     */
    public regis() {
        koneksi = new koneksi();
        initComponents();
    }
    
    public void register() {
        String username = JUSERNAME.getText(); // Mengambil nilai dari text field username
        String password = JPASS.getText();     // Mengambil nilai dari text field password
        String no_hp = JNO.getText();       // Mengambil nilai dari text field nomor telepon

        try {
            // Panggil koneksi database
            Connection con = koneksi.con;

            // Query untuk memeriksa apakah username sudah ada
            String checkQuery = "SELECT * FROM akun WHERE Username = ?";
            try (PreparedStatement psCheck = con.prepareStatement(checkQuery)) {
                psCheck.setString(1, username);
                try (ResultSet rsCheck = psCheck.executeQuery()) {
                    if (rsCheck.next()) {
                        // Username sudah ada
                        JOptionPane.showMessageDialog(null, "Username sudah digunakan", "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }
            }

            // Query untuk menyimpan data pengguna baru ke database
            String insertQuery = "INSERT INTO akun (Username, Password, No_hp) VALUES (?, ?, ?)";
            try (PreparedStatement psInsert = con.prepareStatement(insertQuery)) {
                psInsert.setString(1, username);
                psInsert.setString(2, password);
                psInsert.setString(3, no_hp); // Menyimpan nomor telepon

                // Eksekusi query
                int result = psInsert.executeUpdate();
                if (result > 0) {
                    // Registrasi berhasil
                    JOptionPane.showMessageDialog(null, "Registrasi berhasil", "Success", JOptionPane.INFORMATION_MESSAGE);
                    // Menutup form registrasi dan membuka form login
                    this.dispose();
                    new Log().setVisible(true);
                } else {
                    // Registrasi gagal
                    JOptionPane.showMessageDialog(null, "Registrasi gagal, coba lagi", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JUSERNAME = new javax.swing.JTextField();
        JPASS = new javax.swing.JTextField();
        JREGIS = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        JNO = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("REGISTER");

        jLabel2.setText("USERNAME");

        jLabel3.setText("PASSWORD");

        JPASS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPASSActionPerformed(evt);
            }
        });

        JREGIS.setText("REGISTER");
        JREGIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JREGISActionPerformed(evt);
            }
        });

        jLabel4.setText("NO HP");

        JNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JNOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(103, 103, 103)
                        .addComponent(JPASS, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JREGIS)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel2))
                                    .addComponent(jLabel4))
                                .addGap(103, 103, 103)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JUSERNAME)
                                    .addComponent(JNO, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JUSERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JPASS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(JREGIS)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JPASSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPASSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPASSActionPerformed

    private void JNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JNOActionPerformed

    private void JREGISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JREGISActionPerformed
        // TODO add your handling code here:
        register();
    }//GEN-LAST:event_JREGISActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JNO;
    private javax.swing.JTextField JPASS;
    private javax.swing.JButton JREGIS;
    private javax.swing.JTextField JUSERNAME;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
